name: Test
on:
  push:
    branches: ['*']
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        include:
          - { version: 17 }
          - { version: 16 }
    name: PostgreSQL ${{ matrix.version }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    env:
      PGUSER: postgres
    steps:
      - run: pg-start ${{ matrix.version }}
      - uses: actions/checkout@v4

      - run: sudo apt-get install -y --no-install-recommends postgresql-${{ matrix.version }}-pgtap
      - run: psql -c 'CREATE EXTENSION pgtap'
      # Basic regression test.
      - run: pg-build-test

      # Test update.
      - run: 'if [ -d "$UPDATE_FROM" ]; then make uninstall clean updatecheck; fi'

      # Test all, install, test, test-serial, and test-parallel, both from clean
      # repo and repeated with existing build, with and without PARALLEL_CONN=1.
      - run: make uninstall clean all
      - run: make all
      - run: make install
      - run: psql -c 'CREATE EXTENSION pg_modnar'
      - run: pg_prove -r --ext .sql test/sql/
